export const ARTISTS = [
	{
		id: 0,
		name: "Kehlani",
		image: "assets/images/artists/kehlani-mic.jpg",
		pronouns: "She / They",
		city: "Oakland, California",
		genre: "R&B, Hip-Hop, Neo-Soul, Pop",
		bio: " Just an average girl who loves to sing and perform",
	},
	{
		id: 1,
		name: "Frank Ocean",
		image: "assets/images/artists/frank-ocean-mic.jpg",
		pronouns: "He / Him",
		city: "New Orleans, Louisiana",
		genre: "R&B, Alternative R&B, Avant- Pop",
		bio: "A country boy who loves to sing",
	},
	{
		id: 2,
		name: "Janelle Monae",
		image: "assets/images/artists/janelle-yellow.jpg",
		pronouns: "They / Them",
		city: "Kansas City, Kansas",
		genre: "Funk, Psychedelic Soul, Progressive Soul",
		bio: "Just an android trying to survive on Earth",
	},
	{
		id: 3,
		name: "Lil Nas X",
		image: "assets/images/artists/lil-nas-x-yellow.jpg",
		pronouns: "He / Him",
		city: "Lithia Springs, Georgia",
		genre: "Country Rap, Hip Hip-Hop, Trap, Pop",
		bio: "Dancing with the Devil",
	},
	{
		id: 4,
		name: "Hayley Kiyoko",
		image: "assets/images/artists/hayley-kiyoko-yellow.jpg",
		pronouns: "She / Her",
		city: "Los Angeles, California",
		genre: "Dream Pop, Synth Pop",
		bio: "Some people call me lesbian Jesus and I'm not complaining",
	},
	{
		id: 5,
		name: "Ricky Martin",
		image: "assets/images/artists/ricky-martin-mic.jpg",
		pronouns: "He / Him",
		city: "San Juan, Puerto Rico",
		genre: "Latin, Pop, Urban Pop",
		bio: "An island boy trying to make a name for himself",
	},
	{
		id: 6,
		name: "MNEK",
		image: "assets/images/artists/mnek-mic.jpg",
		pronouns: "He / Him",
		city: "Bellingham, London, England",
		genre: "Pop, Dance-Pop, R&B, House, UK Garage",
		bio: "Come vibe with me across the pond",
	},
	{
		id: 7,
		name: "Demi Lovato",
		image: "assets/images/artists/demi-mic.jpg",
		pronouns: "They / Them",
		city: "Albuquerque, New Mexico",
		genre: "Pop, Pop Rock, R&B",
		bio: "Taking life one day at a time",
	},
	{
		id: 8,
		name: "Willow Smith",
		image: "assets/images/artists/willow-guitar.jpg",
		pronouns: "She / Her",
		city: "Miami, Florida",
		genre: "Alternative R&B, Pop Punk, Neo Soul, EDM",
		bio: "Just another girl who loves rocking out from time to time",
	},
];
